version: 1
services:
  web:
    type: python
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      OPENAI_API_KEY: your_openai_api_key
      AWS_ACCESS_KEY: your_aws_access_key
      AWS_SECRET_KEY: your_aws_secret_key
    installCommand: |
      apt-get update && apt-get install -y tesseract-ocr libleptonica-dev